{"uuid": "6ccbe494-dd88-48ea-8b04-9e339025c318", "children": ["c87b041b-9ece-46e1-9736-8f8747c55315", "06460442-f5f3-46d3-bc70-998771c6b0c3"], "befores": [{"name": "get_users_response", "status": "failed", "statusDetails": {"message": "AssertionError: API call failed, expected status code 200.\nassert 401 == 200\n +  where 401 = <Response [401]>.status_code\n", "trace": "  File \"C:\\Users\\Vaishnavi\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Vaishnavi\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Vaishnavi\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vaishnavi\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1149, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vaishnavi\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 923, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vaishnavi\\OneDrive\\Desktop\\Assessment\\trial\\tests\\test_api.py\", line 37, in get_users_response\n    assert response.status_code == 200, \"API call failed, expected status code 200.\"\n"}, "start": 1728568951724, "stop": 1728568952507}], "start": 1728568951724, "stop": 1728568952683}